/**
 * Nội dung tĩnh của site — port 1:1 từ `src-old/data.ts`. Text tiếng Việt giữ
 * nguyên. Ảnh Unsplash remote được thay bằng bản local qua `localImage()`
 * (xem `scripts/download-unsplash.mjs`).
 */
import { localImage } from "@/lib/images";
import type {
  Article,
  BonBepSlide,
  DstationLocation,
  DstationZone,
  Expert,
  Workshop,
} from "@/lib/types";

export const EXPERTS: Expert[] = [
  {
    id: "exp-1",
    name: "BS. CKI Nguyễn Minh Thư",
    role: "Chuyên gia Y học Lối sống & Dinh dưỡng Tế bào",
    category: "anvie",
    categoryLabel: "Anvie Health & Gobio",
    avatar: localImage(
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop",
    ),
    experience: "12 năm kinh nghiệm",
    rating: 4.9,
    reviewsCount: 148,
    location: "Dstation Hai Bà Trưng, Hà Nội",
    bio: "Bác sĩ chuyên khoa I chuyên về Y học lối sống, cố vấn dinh dưỡng thực dưỡng và phục hồi chuyển hóa tự nhiên cho hàng ngàn gia đình.",
    specialties: [
      "Y học lối sống (Lifestyle Medicine)",
      "Dinh dưỡng vi sinh đường ruột Gobio",
      "Phục hồi bệnh chuyển hóa",
    ],
    certifications: [
      "Chứng chỉ Y học lối sống IBLM Hoa Kỳ",
      "Bác sĩ CKI ĐH Y Hà Nội",
    ],
  },
  {
    id: "exp-2",
    name: "Lê Hoàng Nam",
    role: "Senior Client Advisor (Trưởng nhóm Tư vấn Gia sản)",
    category: "ca",
    categoryLabel: "Client Advisor (CA)",
    avatar: localImage(
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
    ),
    experience: "8 năm kinh nghiệm",
    rating: 5.0,
    reviewsCount: 210,
    location: "Dstation Tây Hồ, Hà Nội",
    bio: "Đồng hành cùng khách hàng thiết lập lộ trình tài chính gia đình, bảo an toàn diện và kết nối các trải nghiệm sống xanh.",
    specialties: [
      "Tư vấn tổng thể 3 Tháp giá trị",
      "Hoạch định ngân sách gia đình",
      "Chăm sóc hội viên D-ONE",
    ],
    certifications: [
      "Chứng chỉ Chuyên gia Hoạch định Gia sản WMA",
      "Top 10 Client Advisor Xuất sắc IPA Living",
    ],
  },
  {
    id: "exp-3",
    name: "Trần Đăng Khoa",
    role: "Chuyên gia Hoạch định Tài chính & Tích sản VNDGO",
    category: "vndgo",
    categoryLabel: "VNDGO - Đầu tư & Đời sống",
    avatar: localImage(
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop",
    ),
    experience: "10 năm kinh nghiệm",
    rating: 4.9,
    reviewsCount: 175,
    location: "Dstation Nguyễn Công Trứ, TP. HCM",
    bio: "Chuyên gia đào tạo Lớp học tài chính VNDGO, tư vấn chiến lược tích lũy định kỳ VNDSIP và bảo vệ dòng tiền nhàn rỗi.",
    specialties: [
      "Chiến lược Tích sản VNDSIP",
      "Quản lý danh mục đầu tư",
      "Hoạch định tài chính hưu trí",
    ],
    certifications: [
      "Chứng chỉ Phân tích Đầu tư CFA Level 2",
      "Chuyên gia Tư vấn VNDIRECT",
    ],
  },
  {
    id: "exp-4",
    name: "Nguyễn Tiến Dũng",
    role: "Giám đốc Thẩm định & Giải pháp Rủi ro PTICare",
    category: "pticare",
    categoryLabel: "PTICare - Bảo hiểm & Đời sống",
    avatar: localImage(
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
    ),
    experience: "14 năm kinh nghiệm",
    rating: 4.8,
    reviewsCount: 132,
    location: "Dstation Hai Bà Trưng, Hà Nội",
    bio: "Chuyên gia cấp cao về thẩm định rủi ro sức khỏe, tài sản doanh nghiệp và hỗ trợ giải quyết quyền lợi bảo hiểm PTI SOS nhanh chóng.",
    specialties: [
      "Bảo hiểm sức khỏe PTI Health",
      "Bảo an tài sản & Nhà tư nhân",
      "Cứu hộ khẩn cấp PTI SOS",
    ],
    certifications: [
      "Chứng chỉ Thẩm định Bảo hiểm Quốc tế ANZIIF",
      "Cố vấn Nghiệp vụ PTI",
    ],
  },
  {
    id: "exp-5",
    name: "Phạm Thu Trang",
    role: "Client Advisor & Chuyên gia Trải nghiệm Lối sống",
    category: "ca",
    categoryLabel: "Client Advisor (CA)",
    avatar: localImage(
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop",
    ),
    experience: "6 năm kinh nghiệm",
    rating: 4.9,
    reviewsCount: 96,
    location: "Dstation Nguyễn Trãi, TP. HCM",
    bio: "Đam mê lan tỏa nếp sống thuận tự nhiên, hướng dẫn các workshop trà đạo, bánh men sống Bếp nhà Delivie và chăm sóc thân tâm.",
    specialties: [
      "Tư vấn dinh dưỡng thực dưỡng Homefood",
      "Điều phối Workshop Dstation",
      "Đồng hành chăm sóc khách hàng",
    ],
    certifications: [
      "Nghệ nhân Trà Dưỡng Sinh",
      "Chứng chỉ Client Advisor Xuất Sắc",
    ],
  },
  {
    id: "exp-6",
    name: "ThS. Dược sĩ Hoàng Bảo Yến",
    role: "Cố vấn Dược liệu Bản địa & Thảo mộc Anvie",
    category: "anvie",
    categoryLabel: "Anvie Health & Gobio",
    avatar: localImage(
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=600",
    ),
    experience: "9 năm kinh nghiệm",
    rating: 5.0,
    reviewsCount: 118,
    location: "Dstation Tây Hồ, Hà Nội",
    bio: 'Nghiên cứu và chuẩn hóa các dòng sản phẩm "Tôi là thảo mộc" và Vietcharm từ thảo dược thiên nhiên nguyên bản Việt Nam.',
    specialties: [
      "Thảo dược bản địa trị liệu",
      "Chăm sóc da & Tóc thuần tự nhiên",
      "Dược thiện phục hồi",
    ],
    certifications: [
      "Thạc sĩ Dược học ĐH Dược Hà Nội",
      "Hội đồng Cố vấn Anvie Gobio",
    ],
  },
];

export const BON_BEP_SLIDES: BonBepSlide[] = [
  {
    id: "bep-homefood",
    subTabId: "bep-homefood",
    title: "1. Bếp Nhà Homefood",
    kitchenName: "Bếp Nhà Homefood",
    badge: "Ăn Đúng Mỗi Ngày",
    badgeColor: "bg-emerald-800 text-white",
    imageUrl: localImage(
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1000&auto=format&fit=crop",
    ),
    caption:
      "Bữa cơm thực dưỡng thuần Việt, nông sản sinh thái xát dối & gia vị Pure lên men tự nhiên.",
  },
  {
    id: "bep-hoa-vi",
    subTabId: "bep-hoa-vi",
    title: "2. Bếp Hoa Vị (GSF)",
    kitchenName: "Bếp Hoa Vị",
    badge: "Kỹ Thuật Ủ · Om · Nén",
    badgeColor: "bg-amber-600 text-white",
    imageUrl: localImage(
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1000&auto=format&fit=crop",
    ),
    caption:
      "Nghệ thuật ẩm thực thưởng vị, mâm cơm ngon đậm đà từ bí đỏ nướng thố đất tỏi Lý Sơn.",
  },
  {
    id: "bep-tri-lieu",
    subTabId: "bep-tri-lieu",
    title: "3. Bếp Trị Liệu",
    kitchenName: "Bếp Trị Liệu",
    badge: "Ohsawa Phục Hồi",
    badgeColor: "bg-teal-700 text-white",
    imageUrl: localImage(
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1000&auto=format&fit=crop",
    ),
    caption:
      "Chế độ ăn nhẹ nhàng giúp cơ thể nghỉ ngơi, đào thải độc tố & phục hồi sinh lực tự nhiên.",
  },
  {
    id: "bep-delivie",
    subTabId: "bep-delivie",
    title: "4. Bếp Delivie",
    kitchenName: "Bếp Delivie",
    badge: "French Levain 48h",
    badgeColor: "bg-sky-700 text-white",
    imageUrl: localImage(
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000&auto=format&fit=crop",
    ),
    caption:
      "Bánh mì men tự nhiên Sourdough chuẩn Pháp, thủy phân gluten giúp êm bụng, dễ tiêu hóa.",
  },
  {
    id: "khong-gian-dstation",
    title: "Không Gian Bốn Bếp",
    kitchenName: "Trải Nghiệm Bốn Bếp",
    badge: "Dstation Experience",
    badgeColor: "bg-indigo-800 text-white",
    imageUrl: localImage(
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=1000&auto=format&fit=crop",
    ),
    caption:
      "Không gian ẩm thực ấm cúng tại Dstation, nơi bạn thưởng thức món lành & trò chuyện nếp sống.",
  },
];

export const WORKSHOPS: Workshop[] = [
  {
    id: "ws-1",
    stt: 1,
    dongWorkshop: "Bếp Nhà AnVie",
    packageName: "Trải Nghiệm Bếp Nhà Homefood",
    level: "Gói 1",
    theme: "Hiểu · Chọn · Làm · Ăn",
    title: "Trải Nghiệm Bếp Nhà Homefood",
    description:
      "Hành trình bốn bước để hiểu nguyên liệu, biết cách lựa chọn gia vị, thực hành nấu cơm gạo lứt và canh miso, rồi cùng thưởng thức một bữa ăn Homefood.",
    price: "450.000",
    priceNumber: 450000,
    duration: "—",
    capacity: "10–40",
    format: "Offline",
    host: "Mrs Phùng Thị Liên",
    gift: "Quà 200.000đ",
    date: "Thứ 7 hàng tuần",
    time: "09:00 - 12:00",
    location: "Dstation & Bếp Homefood",
    image: localImage(
      "https://images.unsplash.com/photo-1556911073-38141963c9e0?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 12,
    note: "Tặng bộ quà Homefood trị giá 200.000đ",
  },
  {
    id: "ws-2",
    stt: 2,
    dongWorkshop: "Bếp Nhà AnVie",
    packageName: "Thức Tỉnh Căn Bếp",
    level: "Gói 2",
    theme: "Thay đổi nhỏ — tác động lớn",
    title: "Thức Tỉnh Căn Bếp",
    description:
      "Cùng nhìn lại những lựa chọn quen thuộc trong căn bếp, tìm hiểu sự khác biệt giữa các nhóm gia vị và thực phẩm, từ đó điều chỉnh thói quen theo hướng lành và cân bằng hơn.",
    price: "350.000",
    priceNumber: 350000,
    duration: "—",
    capacity: "10–40",
    format: "Offline",
    host: "Mrs Phùng Thị Liên",
    gift: "Quà 100.000đ",
    date: "Chủ Nhật hàng tuần",
    time: "14:00 - 16:30",
    location: "Dstation & Bếp Homefood",
    image: localImage(
      "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 15,
    note: "Tặng bộ quà gia vị sạch trị giá 100.000đ",
  },
  {
    id: "ws-3",
    stt: 3,
    dongWorkshop: "Bếp Nhà AnVie",
    packageName: "Chạm Vị Thật",
    level: "Gói 3",
    theme: "Để cơ thể tự trả lời",
    title: "Chạm Vị Thật",
    description:
      "Set ăn Homefood để lắng nghe cơ thể — nhẹ bụng, thư giãn, dễ chịu.",
    price: "250.000",
    priceNumber: 250000,
    duration: "—",
    capacity: "10–40",
    format: "Offline",
    host: "Mrs Phùng Thị Liên",
    gift: "—",
    date: "Hàng ngày theo đăng ký",
    time: "11:30 - 13:30 / 18:00 - 20:00",
    location: "Nhà hàng Hoa Vị Mộc / Hoa Vị Xưa",
    image: localImage(
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 20,
  },
  {
    id: "ws-4",
    stt: 4,
    dongWorkshop: "Trà Vietcharm",
    packageName: "Thưởng Trà An Yên",
    level: "Gói 1 · Nhập môn",
    theme: "Một khoảng lặng nhẹ nhàng",
    title: "Thưởng Trà An Yên",
    description:
      "Thả lỏng, đánh thức giác quan bằng trà cổ thụ, thưởng cùng bánh truyền thống.",
    price: "150.000",
    priceNumber: 150000,
    duration: "60 phút",
    capacity: "5–20",
    format: "Offline",
    host: "Toàn bộ Host",
    gift: "—",
    date: "Hàng tuần",
    time: "15:00 - 16:00",
    location: "Không gian Trà Vietcharm tại Dstation",
    image: localImage(
      "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 8,
  },
  {
    id: "ws-5",
    stt: 5,
    dongWorkshop: "Trà Vietcharm",
    packageName: "Khởi Nguồn Di Sản",
    level: "Gói 2",
    theme: "Nhập môn thưởng trà",
    title: "Khởi Nguồn Di Sản",
    description:
      "Câu chuyện rừng trà cổ thụ, nhận biết dòng trà, tự pha một ấm chuẩn vị.",
    price: "300.000",
    priceNumber: 300000,
    duration: "90 phút",
    capacity: "10–15",
    format: "Offline",
    host: "Toàn bộ Host",
    gift: "—",
    date: "Thứ 5 & Thứ 7 hàng tuần",
    time: "09:30 - 11:00",
    location: "Không gian Trà Vietcharm tại Dstation",
    image: localImage(
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 10,
  },
  {
    id: "ws-6",
    stt: 6,
    dongWorkshop: "Trà Vietcharm",
    packageName: "Trải Nghiệm Tinh Hoa Trà Cổ",
    level: "Gói 3 · Chuyên sâu",
    theme: "Cảm nhận trọn vẹn di sản",
    title: "Trải Nghiệm Tinh Hoa Trà Cổ",
    description:
      "Đi sâu trà cổ, trà dưỡng sinh theo thể trạng, nghệ thuật bài trí bàn trà.",
    price: "500.000",
    priceNumber: 500000,
    duration: "120 phút",
    capacity: "5–10",
    format: "Offline",
    host: "Trà nương Phan Thị Duyên · Nguyễn Thúy Nga",
    gift: "—",
    date: "Thứ 7 hàng tuần",
    time: "14:30 - 16:30",
    location: "Trà thất Dstation VIP Room",
    image: localImage(
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 6,
    note: "Giới hạn 5-10 người để đảm bảo trải nghiệm sâu sắc",
  },
  {
    id: "ws-7",
    stt: 7,
    dongWorkshop: "Trà & Bánh",
    packageName: "Slow Living with Tea & Bread",
    level: "Basic",
    theme: "Nhịp sống chậm — Trà & Bánh",
    title: "Slow Living with Tea & Bread",
    description:
      "Trải nghiệm sự kết hợp giữa trà Vietcharm và bánh Pháp Delivie, từ Coldbrew đến trà nóng, cùng hoạt động tự tay hoàn thiện và thưởng thức bánh tại chỗ.",
    price: "250.000",
    priceNumber: 250000,
    duration: "60–90 phút",
    capacity: "5–20",
    format: "Offline",
    host: "Trà nương · GĐ SP Phan Thị Duyên",
    gift: "Voucher 20% Delivie frozen",
    date: "Chiều Thứ 6 hàng tuần",
    time: "15:00 - 16:30",
    location: "Bistro Dstation & Bếp Delivie",
    image: localImage(
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 10,
    note: "Tặng Voucher 20% Delivie frozen",
  },
  {
    id: "ws-8",
    stt: 8,
    dongWorkshop: "Trà & Bánh",
    packageName: "The Natural Masterpiece",
    level: "Premium",
    theme: "Pairing Trà Shan & bánh men tự nhiên",
    title: "The Natural Masterpiece",
    description:
      "Khám phá cuộc gặp gỡ giữa trà Shan Tuyết Việt Nam và bánh men tự nhiên kiểu Pháp, tìm hiểu men Levain và thưởng thức thực đơn kết hợp trà – bánh được tuyển chọn.",
    price: "500.000",
    priceNumber: 500000,
    duration: "60–90 phút",
    capacity: "< 15",
    format: "Offline",
    host: "Chuyên gia bánh Pháp — Mr Quentin",
    gift: "Voucher 20% Delivie frozen",
    date: "Thứ 7 cách tuần",
    time: "09:30 - 11:00",
    location: "Bếp Bánh Men Tự Nhiên Delivie",
    image: localImage(
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 8,
    note: "Trải nghiệm men Levain cùng Chuyên gia bánh Pháp Mr Quentin",
  },
  {
    id: "ws-9",
    stt: 9,
    dongWorkshop: "Tôi Là Thảo Mộc",
    packageName: "Tôi Là Thảo Mộc",
    level: "Basic",
    theme: "Chăm sóc Thân – Tâm – Trí",
    title: "Tôi Là Thảo Mộc",
    description:
      "Khám phá những thảo mộc bản địa quen thuộc, tìm hiểu tri thức chăm sóc dân gian và cách các giá trị ấy được tiếp nối trong đời sống hôm nay.",
    price: "150.000",
    priceNumber: 150000,
    duration: "90 phút",
    capacity: "20–50",
    format: "Offline",
    host: "CDA Host · IDO",
    gift: "—",
    date: "Chủ Nhật hàng tuần",
    time: "09:00 - 10:30",
    location: "Không gian Sinh thái Dstation",
    image: localImage(
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 25,
  },
  {
    id: "ws-10",
    stt: 10,
    dongWorkshop: "Tôi Là Thảo Mộc",
    packageName: "Thảo Mộc Nước Nam",
    level: "Premium",
    theme: "Hành trình tái tạo bản nguyên",
    title: "Thảo Mộc Nước Nam",
    description:
      "Tìm hiểu nguồn thảo mộc bản địa, cách nuôi trồng và hành trình phát triển thành những giải pháp sinh học ứng dụng trong chăm bếp, chăm nhà và chăm sóc cơ thể.",
    price: "250.000",
    priceNumber: 250000,
    duration: "90–120 phút",
    capacity: "> 30",
    format: "Offline",
    host: "Mrs Nguyễn Thanh Phương",
    gift: "—",
    date: "Thứ 7 tuần thứ 2 & 4 hàng tháng",
    time: "14:00 - 16:00",
    location: "Hội trường Trải nghiệm Sinh thái Dstation",
    image: localImage(
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=600",
    ),
    tower: "suc-khoe",
    status: "upcoming",
    spotsLeft: 30,
    note: "Khám phá thảo dược bản địa và giải pháp chăm sóc gia đình tự nhiên",
  },
];

export const ARTICLES: Article[] = [
  {
    id: "art-1",
    title:
      "AnVie Gobio: Xu hướng dinh dưỡng tự nhiên hỗ trợ hệ tiêu hóa vượt trội",
    excerpt:
      'Hệ tiêu hóa chính là "bộ não thứ hai" của cơ thể. Tìm hiểu cách các dòng sản phẩm vi sinh hữu cơ AnVie Gobio tái cấu trúc hệ sinh thái vi khuẩn đường ruột lành mạnh.',
    content:
      'Hệ tiêu hóa chính là "bộ não thứ hai" của cơ thể. Tìm hiểu cách các dòng sản phẩm vi sinh hữu cơ AnVie Gobio tái cấu trúc hệ sinh thái vi khuẩn đường ruột lành mạnh. Một lối sống khỏe mạnh bắt đầu bằng việc hiểu rõ nhu cầu hấp thu dinh dưỡng tự nhiên và hạn chế tối đa các chất bảo quản tổng hợp.',
    category: "suc-khoe",
    author: "Bác sĩ Minh Thư - Ban y khoa AnVie Health",
    date: "18/07/2026",
    readTime: "5 phút đọc",
    image: localImage(
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600",
    ),
  },
  {
    id: "art-2",
    title: "Lợi ích kép từ Tích lũy định kỳ VNDSIP trong thời kỳ lạm phát",
    excerpt:
      "Làm thế nào để dòng tiền nhàn rỗi của bạn tự động sinh trưởng an toàn? VNDSIP giới thiệu chiến lược gieo hạt tài chính định kỳ giúp bình ổn tâm lý trước biến động thị trường.",
    content:
      "Làm thế nào để dòng tiền nhàn rỗi của bạn tự động sinh trưởng an toàn? VNDSIP giới thiệu chiến lược gieo hạt tài chính định kỳ giúp bình ổn tâm lý trước biến động thị trường. Tích sản đều đặn tạo thói quen đầu tư văn minh và gặt hái quả ngọt vững chãi trong dài hạn.",
    category: "thinh-vuong",
    author: "Trần Đăng Khoa - Chuyên gia Hoạch định Gia sản VNDIRECT",
    date: "12/07/2026",
    readTime: "6 phút đọc",
    image: localImage(
      "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=600",
    ),
  },
  {
    id: "art-3",
    title: "Lá chắn PTI SOS: Giải pháp cứu hộ y tế khẩn cấp 24/7 bạn cần có",
    excerpt:
      "Rủi ro là những điều không báo trước. PTI SOS được xây dựng để cung cấp giải pháp can thiệp, hỗ trợ di chuyển và chăm sóc khẩn cấp một cách nhanh chóng nhất.",
    content:
      "Rủi ro là những điều không báo trước. PTI SOS được xây dựng để cung cấp giải pháp can thiệp, hỗ trợ di chuyển và chăm sóc khẩn cấp một cách nhanh chóng nhất. Mang đến sự an tâm tuyệt đối cho bạn và gia đình trên mỗi dặm đường hay trong công việc kinh doanh.",
    category: "bao-an",
    author: "Nguyễn Tiến Dũng - Giám đốc Nghiệp vụ PTI",
    date: "15/07/2026",
    readTime: "4 phút đọc",
    image: localImage(
      "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=600",
    ),
  },
  {
    id: "art-4",
    title: "Hiểu đúng về Y học lối sống: Đẩy lùi bệnh tật từ gốc rễ",
    excerpt:
      "Y học lối sống (Lifestyle Medicine) là nhánh khoa học tập trung vào 6 trụ cột cốt lõi để duy trì sức khỏe tối ưu và đảo ngược các bệnh mãn tính.",
    content:
      "Y học lối sống tập trung vào chế độ ăn thực vật toàn phần, hoạt động thể chất đều đặn, giấc ngủ chất lượng, kiểm soát căng thẳng, tránh các chất độc hại và kết nối xã hội tích cực. AnVie Life đồng hành cùng bạn thiết lập kỷ luật nếp sống tự nhiên.",
    category: "suc-khoe",
    author: "AnVie Life Editorial",
    date: "08/07/2026",
    readTime: "8 phút đọc",
    image: localImage(
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=600",
    ),
  },
];

export const D_STATION_ZONES: DstationZone[] = [
  {
    id: "zone-1",
    title: "Zone 1: Khám phá",
    description:
      "Tìm hiểu hệ sinh thái IPA Living cùng các giải pháp Sống Khỏe – Sống Giàu – Sống An.",
    iconName: "Compass",
    colorClass:
      "text-emerald-800 border-emerald-200 bg-emerald-50/60 hover:bg-emerald-100/60",
    details: [],
  },
  {
    id: "zone-2",
    title: "Zone 2: Trải nghiệm",
    description:
      "Thưởng thức sản phẩm, tham gia workshop và cảm nhận những giá trị bằng chính trải nghiệm của mình.",
    iconName: "Sparkles",
    colorClass:
      "text-amber-800 border-amber-200 bg-amber-50/60 hover:bg-amber-100/60",
    details: [],
  },
  {
    id: "zone-3",
    title: "Zone 3: Tư vấn",
    description:
      "Được lắng nghe và đồng hành bởi đội ngũ Client Advisor để lựa chọn giải pháp phù hợp với nhu cầu của bạn.",
    iconName: "UserCheck",
    colorClass: "text-sky-800 border-sky-200 bg-sky-50/60 hover:bg-sky-100/60",
    details: [],
  },
  {
    id: "zone-4",
    title: "Zone 4: Kết nối",
    description:
      "Không gian dành cho cộng đồng, nơi những người cùng giá trị gặp gỡ, chia sẻ và truyền cảm hứng cho nhau.",
    iconName: "Users",
    colorClass:
      "text-indigo-800 border-indigo-200 bg-indigo-50/60 hover:bg-indigo-100/60",
    details: [],
  },
];

export const D_STATION_LOCATIONS: DstationLocation[] = [
  {
    id: "loc-hn-01",
    orderNumber: "01",
    name: "Dstation Trần Thái Tông",
    address: "95 Trần Thái Tông, Cầu Giấy, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Cầu Giấy",
    province: "Hà Nội",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.tranthaitong",
  },
  {
    id: "loc-hn-02",
    orderNumber: "02",
    name: "Dstation Nguyễn Thượng Hiền",
    address: "Số 1 Nguyễn Thượng Hiền, Hai Bà Trưng, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Hai Bà Trưng",
    province: "Hà Nội",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.nth",
  },
  {
    id: "loc-hn-03",
    orderNumber: "03",
    name: "Dstation TimeCity",
    address:
      "Tòa Park 7, P. Minh Khai, Khu đô thị Times City, Hai Bà Trưng, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Hai Bà Trưng",
    province: "Hà Nội",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.timescity",
  },
  {
    id: "loc-hn-04",
    orderNumber: "04",
    name: "Dstation Lê Văn Lương",
    address: "Tòa nhà CT1 số 43 Lê Văn Lương, Thanh Xuân, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Thanh Xuân",
    province: "Hà Nội",
    category: "dstation",
  },
  {
    id: "loc-hn-05",
    orderNumber: "05",
    name: "Dstation Âu Lạc",
    address: "Số 2 N7B, Trung Hòa - Nhân Chính, Thanh Xuân, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Thanh Xuân",
    province: "Hà Nội",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.AL",
  },
  {
    id: "loc-hn-06",
    orderNumber: "06",
    name: "Dstation Nguyễn Chí Thanh",
    address: "76 Nguyễn Chí Thanh, Láng, Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Láng",
    province: "Hà Nội",
    category: "dstation",
    mapsLink:
      "https://www.google.com/maps/place/Dstation+Nguy%E1%BB%85n+Ch%C3%AD+Thanh/data=!4m2!3m1!1s0x0:0xa0feba394194c635?sa=X&ved=1t:2428&ictx=111",
    facebookLink: "https://www.facebook.com/dstation.AL",
  },
  {
    id: "loc-hn-07",
    orderNumber: "07",
    name: "Dstation Trúc Khê",
    address: "19 Trúc Khê - Láng - Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Láng",
    province: "Hà Nội",
    category: "dstation",
  },
  {
    id: "loc-hn-08",
    orderNumber: "08",
    name: "Nhà hàng HOA VỊ MỘC",
    address: "Số 19 Trúc Khê - phường Láng - Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Láng",
    province: "Hà Nội",
    category: "hoavi",
    facebookLink: "https://www.facebook.com/hoavi.restaurant",
  },
  {
    id: "loc-hn-09",
    orderNumber: "09",
    name: "Nhà hàng HOA VỊ XƯA",
    address: "Số 10 Duy Tân - Cầu Giấy - Hà Nội",
    city: "hanoi",
    cityName: "Hà Nội",
    district: "Cầu Giấy",
    province: "Hà Nội",
    category: "hoavi",
  },
  {
    id: "loc-hcm-01",
    orderNumber: "10",
    name: "Dstation Pasteur",
    address: "90 Pasteur, Phường Sài Gòn, TP.HCM",
    city: "hcm",
    cityName: "TP.HCM",
    district: "Phường Sài Gòn",
    province: "TP.HCM",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.pasteur",
  },
  {
    id: "loc-hcm-02",
    orderNumber: "11",
    name: "Dstation Sala - Thủ Đức",
    address: "1-3 Đường số B4, Phường An Khánh, TP.HCM",
    city: "hcm",
    cityName: "TP.HCM",
    district: "Phường An Khánh",
    province: "TP.HCM",
    category: "dstation",
    facebookLink: "https://web.facebook.com/dstation.thuduc/",
  },
  {
    id: "loc-hcm-03",
    orderNumber: "12",
    name: "Dstation Nguyễn Xí",
    address: "205 Nguyễn Xí, Phường Bình Thạnh, TP.HCM",
    city: "hcm",
    cityName: "TP.HCM",
    district: "Phường Bình Thạnh",
    province: "TP.HCM",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.nguyenxi.hcm/",
  },
  {
    id: "loc-hcm-04",
    orderNumber: "13",
    name: "Nhà hàng HOA VỊ XƯA - HCM",
    address: "Số 78 Nguyễn Đình Chiểu - Tân Định - TP.HCM",
    city: "hcm",
    cityName: "TP.HCM",
    district: "Tân Định",
    province: "TP.HCM",
    category: "hoavi",
  },
  {
    id: "loc-oth-01",
    orderNumber: "14",
    name: "Dstation Bình Dương",
    address:
      "Số 63 đường D9, KDC Chánh Nghĩa, khu 11, phường Chánh Nghĩa, TP. Thủ Dầu Một, tỉnh Bình Dương",
    city: "other",
    cityName: "Bình Dương",
    district: "TP. Thủ Dầu Một",
    province: "Bình Dương",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.binhduong/",
  },
  {
    id: "loc-oth-02",
    orderNumber: "15",
    name: "Dstation Đà Nẵng",
    address:
      "Phòng 5A Tầng 5 Tòa nhà Rico, 363 Nguyễn Hữu Thọ, Cẩm Lệ, Đà Nẵng",
    city: "other",
    cityName: "Đà Nẵng",
    district: "Cẩm Lệ",
    province: "Đà Nẵng",
    category: "dstation",
  },
  {
    id: "loc-oth-03",
    orderNumber: "16",
    name: "Dstation Hải Phòng",
    address: "5 Nguyễn Tri Phương, TP Hải Phòng",
    city: "other",
    cityName: "Hải Phòng",
    district: "Hải Phòng",
    province: "Hải Phòng",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.hp",
  },
  {
    id: "loc-oth-04",
    orderNumber: "17",
    name: "Dstation Hòa Bình",
    address:
      "Số 14, ngõ 291, đường Trần Hưng Đạo, tổ 7, phường Quỳnh Lâm, TP Hòa Bình, Tỉnh Hoà Bình",
    city: "other",
    cityName: "Hòa Bình",
    district: "Quỳnh Lâm",
    province: "Hòa Bình",
    category: "dstation",
  },
  {
    id: "loc-oth-05",
    orderNumber: "18",
    name: "Dstation Ecopark",
    address: "155A Thuỷ Nguyên - Ecopark - Hưng Yên",
    city: "other",
    cityName: "Hưng Yên",
    district: "Ecopark",
    province: "Hưng Yên",
    category: "dstation",
    facebookLink:
      "https://web.facebook.com/share/1874rZ8gqq/?mibextid=wwXIfr&_rdc=1&_rdr",
  },
  {
    id: "loc-oth-06",
    orderNumber: "19",
    name: "Dstation Vinh",
    address:
      "Số 2, ngõ 128 đường Hermann, khối Yên Vinh, P. Trường Vinh, Nghệ An",
    city: "other",
    cityName: "Nghệ An",
    district: "P. Trường Vinh",
    province: "Nghệ An",
    category: "dstation",
  },
  {
    id: "loc-oth-07",
    orderNumber: "20",
    name: "Dstation Nam Định",
    address: "Số 88 – 90 phố Phạm Sư Mạnh, Phường Nam Định, Tỉnh Ninh Bình",
    city: "other",
    cityName: "Ninh Bình",
    district: "Phường Nam Định",
    province: "Ninh Bình",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.namdinh",
  },
  {
    id: "loc-oth-08",
    orderNumber: "21",
    name: "Dstation Yên Tử",
    address:
      "Sân đình Làng Nương, khu lưu trú Tùng Lâm Yên Tử, xã Thượng Yên Công, thành phố Uông Bí, Hạ Long",
    city: "other",
    cityName: "Quảng Ninh",
    district: "Uông Bí",
    province: "Quảng Ninh",
    category: "dstation",
  },
  {
    id: "loc-oth-09",
    orderNumber: "22",
    name: "Dstation Thanh Hóa",
    address: "Số 11 Hạc Thành, Phường Hạc Thành, Thanh Hóa",
    city: "other",
    cityName: "Thanh Hóa",
    district: "Phường Hạc Thành",
    province: "Thanh Hóa",
    category: "dstation",
    facebookLink: "https://www.facebook.com/dstation.th",
  },
  {
    id: "loc-oth-10",
    orderNumber: "23",
    name: "Dstation Huế",
    address:
      "Thửa Đất số 19, tờ bản đồ số 41, Khu định cư Bàu Vá giai đoạn 2 (Đợt 3), Phường Thuận Hòa, Thành phố Huế",
    city: "other",
    cityName: "Thừa Thiên Huế",
    district: "Phường Thuận Hòa",
    province: "Thừa Thiên Huế",
    category: "dstation",
  },
];
